---
- name: Deploy App
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Log in to ECR
      command: "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 751212661018.dkr.ecr.us-east-1.amazonaws.com"
    - name: Pull Docker image from ECR
      command: "docker pull 751212661018.dkr.ecr.us-east-1.amazonaws.com/front:latest"
    - name: Run Docker container
      docker_container:
        name: my-app-container
        image: "751212661018.dkr.ecr.us-east-1.amazonaws.com/front:latest"
        state: started
        ports:
          - "3000:3000"
        restart_policy: always
        network_mode: host
