apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 050812282329.dkr.ecr.us-east-1.amazonaws.com/avt-api:latest
          ports:
            - containerPort: 3030
          
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
    - port: 3030
      targetPort: 3030
  selector:
    app: api
