apiVersion: apps/v1
kind: Deployment
metadata:
  name: avt-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: avt-api
  template:
    metadata:
      labels:
        app: avt-api
    spec:
      containers:
        - name: avt-api
          image: docker_kubernetes-api:latest
          ports:
            - containerPort: 80
