apiVersion: apps/v1
kind: Deployment
metadata:
  name: avt-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: avt-api
  template:
    metadata:
      labels:
        app: avt-api
    spec:
      containers:
        - name: avt-api
          image: vitoradams/avt-api:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: avt-api-service
spec:
  selector:
    app: avt-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
