apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: 050812282329.dkr.ecr.us-east-1.amazonaws.com/front:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: LoadBalancer
  selector:
    app: front-end
  ports:
    - port: 80
      targetPort: 3000
