version: "3.3"

services:

  db:
    container_name: postgres_avt_test
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avt_db
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
    ports:
      - "5432:5432"
    restart: always