name: ApiPipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls -la

      - name: Install dependencies
        run: |
          cd api
          npm install -g yarn
          yarn install

      - name: Validate ESlint
        run: |
          cd api
          yarn lint --fix

      - name: Format the code
        run: |
          cd api
          yarn format

      - name: Build
        run: |
          cd api
          yarn build
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls -la

      - name: Install dependencies
        run: |
          cd api
          npm install -g yarn
          yarn install

      - name: Prepare .env to test
        run: |
          touch .env
          echo PORT=3030 >> .env
          echo SECRET=GSJFDHG827FSDBNGLKWY0R982423TKJGHWS98R7-254 >> .env
          echo DATABASE_URL="file:./dev.sqlite" >> .env
          echo APP_ENV=dev >> .env
          echo RESEND_SECRET=${{ secrets.RESEND_TOKEN }} >> .env

      - name: Prepare Prisma to test
        run: |
          npx prisma generate --schema ./test/prisma/schema-test.prisma
          npx prisma db push --schema ./test/prisma/schema-test.prisma

      - name: Test
        run: |
          yarn test:e2e
  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls -la

      - name: Install dependencies
        run: |
          cd api
          npm install -g yarn
          yarn install

      - name: Prepare .env to deploy
        run: |
          touch .env
          echo PORT=3030 >> .env
          echo SECRET=GSJFDHG827FSDBNGLKWY0R982423TKJGHWS98R7-254 >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo APP_ENV=prod >> .env
          echo RESEND_SECRET=${{ secrets.RESEND_TOKEN }} >> .env

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME_IMAGE }}/avt-api:latest ./api
        working-directory: ./api

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME_IMAGE }}/avt-api:latest
